### ISSUE TITLE
Add markers to the graphs

### ISSUE THREAD

**Issue by acs** [HumbleSoftware/envisionjs#13]
One cool thing in flotr2 is how you can mark graphs using the marker graph. The marker type is not included in envision, but you can include it by hand. But the main problem is that you can not show two graphs at the same time in a container, like it is done in the [advanced markers example](http://localhost/reports/flotr2/HumbleSoftware-Flotr2-638eb64/examples/dev.html#!advanced-markers).

I have concluded that it is need to add support for this in Component "draw : function (data, config)". Any idea about how to implement it will help in my development.

Cheers

**Comment by acs** [comment]
You can add markers inside the same graph:

```
function getDefaults () {
  return {
    commits : {
      name : 'swscopio-commits-commits',
      config : {
        //colors: ['#00A8F0', '#C0D800', '#CB4B4B', '#4DA74D', '#9440ED'],
        colors: ['#ffa500', '#00ff00',  '#CB4B4B', '#4DA74D', '#9440ED'],
        'lite-lines' : {
...
        },
        'markers': {
            show: true,
            position: 'ct'
        },
...
    }
...
  }
}
```

and you are done! Nice!

**Comment by cesutherland** [comment]
I think that you can... just have to pass each data series as an object (or
update the config to show both).

-Carl

On Sun, Aug 5, 2012 at 7:01 PM, Alvaro del Castillo <
reply@reply.github.com
