### ISSUE TITLE
Multichart

### ISSUE THREAD

**Issue by svieujot** [HumbleSoftware/envisionjs#15]
I am trying to create a chart similar to the financial one ( http://www.humblesoftware.com/envision/demos/finance ), with several lines ( like this : http://www.humblesoftware.com/flotr2/index#!basic ) in the top chart.

The Flotr adapter seems to be hard wired to take only one serie of data.
Is there a way to do this easily ?

I am trying to do a custom adapter derived from the Flotr adapter, but it is a hard learning curve.

Any advice ?

**Comment by cesutherland** [comment]
Here's an example with multiple lines:
http://jsfiddle.net/cesutherland/LurmY/49/  WIth this one again, you may
want to skipPreprocess, if the x-values for the two series are not the same.

We'll want to be able to downsample with large series that don't share an
x-axis but right now this isn't tested.

-c

**Comment by svieujot** [comment]
So far my series share rhe same x values.
My problem is that they have different styles : one is candles, the other is a line.
I did not find a way to pass this to the Flotr adapter.
Is there a way to do this ?
For example in your multiline, example, how could you use bars for the green line ?

Thank you.

**Comment by cesutherland** [comment]
Here you are:

http://jsfiddle.net/LurmY/75/

Each series is configurable also as an object with a data attribute.

**Comment by svieujot** [comment]
Great !

Thank you very much for your help.

**Comment by svieujot** [comment]
A few more things on the multigraph :

I am trying to use the right most y axis (y2axis) for the labels, but it does not seem to work.

I am also trying to display the labels.
It works fine for the "sub-series", but not for the first one.

Any clue on this ?

Thank you !
