### ISSUE TITLE
envision.min.js breaks some Flotr options

### ISSUE THREAD

**Issue by Frozenlock** [HumbleSoftware/envisionjs#19]
I believe envision.min.js breaks some Flotr options.
Take this example: http://jsfiddle.net/cesutherland/u7QB4/1/

If you change envision.js for envision.min.js, the grids will disappear.

**Comment by cesutherland** [comment]
Grid must be included after `envision.min.js`

Check out http://jsfiddle.net/u7QB4/4/

**Comment by Frozenlock** [comment]
Oh wow!
Not only did I missed that, but I didn't even realized that grid.js must be included separately from envision.min.js.

Thank you very much for his AND the library, awesome work :-)

**Comment by cesutherland** [comment]
Cheers!
