### ISSUE TITLE
Hability to make realtime graphs

### ISSUE THREAD

**Issue by alejandro** [HumbleSoftware/envisionjs#2]
Howdy! Currently I'm working in a kind of dashboard with data which is changing constantly, in other words, changing in realtime. I was reading through your docs and I didn't found anything about this topic, so what is the status of envision to make realtime graphs. Or what's the way to make a envision graph more faster in every data change. Asuming new data every 2 secs.

Cheers.

**Comment by cesutherland** [comment]
Sounds like a cool project.

I will be adding an animation component to envision which will make this easier.  For now however, the data management and animation is left mostly up to the user.  Are you building a custom graph by hand or are you using the TimeSeries template?

I will put up an example.

**Comment by cesutherland** [comment]
Here you go: http://humblesoftware.com/envision/demos/realtime

Again, I'll wrap up a lot of this functionality as an animation class but everything takes some time!  Good news is it isn't an excessive amount of work to write it out manually.

**Comment by alejandro** [comment]
Awesome @cesutherland ! :) Definetely I'll take a look at it, and I'll let you know when my dashboard is done... KUDOS
