### ISSUE TITLE
BUG: selection callback does not work with TimeSeries template

### ISSUE THREAD

**Issue by powder96** [HumbleSoftware/envisionjs#7]
I want to set a selection callback function (this feature is used in the ajax example) for a chart, based on TimeSeries template but I'm sure that only Finance template supports that function. The problem is that other templates do not have this code:

<pre>
function Finance (options) {
  // ...
  selection
  // ...
    .add(V.actions.selection, options.selectionCallback ? { callback : options.selectionCallback } : null);
  // ...
})();
</pre>

**Comment by cesutherland** [comment]
I've added the callback.
