### ISSUE TITLE
FEATURE REQUEST: grids on charts

### ISSUE THREAD

**Issue by powder96** [HumbleSoftware/envisionjs#8]
I suggest to add an option to draw grids on charts. It is the same thing as in Flotr2: http://www.humblesoftware.com/flotr2/index#!basic

**Comment by cesutherland** [comment]
You can do this by including the grid plugin for Flotr2 and configuring the appropriate chart.

**Comment by cesutherland** [comment]
http://jsfiddle.net/cesutherland/u7QB4/1/

**Comment by powder96** [comment]
Thanks!
